README.md, cmd/manager/main.go, deploy/operator.yaml, examples/cluster_custom_domain.yaml, pkg/apis/customdomain/v1alpha1/customdomain_types.go, pkg/controller/customdomain/customdomain_controller_test.go, pkg/controller/customdomain/customdomain_vars.go, test/foo_custom_domain.yaml, test/my_custom_domain.yaml
Updates README to remove personal registry instructions and makes it more generic. Fixed `go fmt` errors.
=> Clean Up Readme And Fix Formating/Linting Errors

build/Dockerfile
Because the _build_ and _build-image_ stages in prow are separate the operator binary is not available to the docker build command. This PR uses multistage builds to make the image build easier.
=> Use multistage build in docker to build the operator binary

pkg/apis/customdomain/v1alpha1/customdomain_types.go, pkg/controller/customdomain/customdomain_controller.go, pkg/controller/customdomain/customdomain_controller_test.go, pkg/controller/customdomain/customdomain_utils.go
Protect from adding/deleting hive/cloud-ingress-operator managed ingresscontrollers (default, apps2). 
Add labels to managed resources.
=> Managed IngressController Pre-Checks

deploy/05_prom_k8s_role.yaml, deploy/06_prom_k8s_rolebinding.yaml, hack/generate-operator-bundle.py
This will add the appropriate prometheus-k8s rbac rules to the bundle output directory for OLM to deploy with.
=> Add Prometheus-k8s RBAC Files

pkg/controller/customdomain/customdomain_controller.go
This PR ensures any ingresscontrollers created by CDO will be scheduled to infra nodes. It updates the NodePlacement spec to use the standard nodeselector and toleration to schedule pods onto infra nodes.
=> [OSD-6581] Add infra nodeSelector and toleration to IngressController

deploy/04_operator.yaml
This adds infra scheduling selectors to the deployment of the custom domain operator.
=> Add infra nodeAffinity to operator deployment

deploy/crds/managed.openshift.io_customdomains_crd.yaml, pkg/apis/customdomain/v1alpha1/customdomain_types.go
This ensures that scope is not required and that we do not use default via kubebuilder (not supported for this version of operator-sdk).
=> Fix CRD for CustomDomain

go.mod, pkg/apis/customdomain/v1alpha1/doc.go, pkg/apis/customdomain/v1alpha1/zz_generated.openapi.go
This fixes the openapi to return descriptions for the CRD fields for `oc explain`
[OSD-7057](https://issues.redhat.com/browse/OSD-7057)
=> Add k8s annotations to generate docs for oc explain

cmd/manager/main.go, go.mod
This fixes an error on startup as the osdMetrics library requires v1.ServiceMonitor to be registered.
=> Add prometheus monitoring to scheme for v1.ServiceMonitor for osdMetrics

deploy/crds/managed.openshift.io_customdomains_crd.yaml, pkg/apis/customdomain/v1alpha1/customdomain_types.go, pkg/apis/customdomain/v1alpha1/zz_generated.openapi.go
This should fix the CRD schema validations on upgrade.
=> Make status.scope optional

hack/olm-registry/olm-artifacts-template.yaml, hack/templates/selectorsyncset.yaml
The custom domains operator was not being installed on gcp clusters due to an extraneous `matchlabel` which restricted it aws. Removing this label should allow the operator be installed on any platform supported by OSD.
=> OSD-7231 - Removed aws matchlabel to allow installation on gcp.

pkg/controller/customdomain/customdomain_controller.go, pkg/controller/customdomain/customdomain_controller_test.go
Adds object name validation to reconcile loop per https://issues.redhat.com/browse/OSD-7156. 
The regex used was taken directly from the ingress-operator, which requires a DNS-1035 label & blocks the creation of a customdomain if the CR's name does not adhere to those standards.
=> OSD-7156 - Restrict object name to DNS-1035 label.

pkg/controller/customdomain/customdomain_controller.go
This prevents the restricted "apps" CustomDomain CR from being created. 
Ref:
https://issues.redhat.com/browse/OSD-7946
=> Prevent restricted 'apps' for CustomDomain CR name

pkg/controller/customdomain/customdomain_controller.go
On upgrades, the default IngressController.Spec.EndpointPublishingStrategy could be empty. This prevents a crash loop due to nil pointer deref.
Ref:
https://issues.redhat.com/browse/OSD-7982
=> Check for Nil pointer deref on Spec.EndpointPublishingStrategy

README.md
Fixing filename in the readme to match the actual file name in deploy/crds/managed.openshift.io_customdomains.yaml
=> Fixing filename

TESTING.md
In this commit, I added steps to test creating customdomain and testing it without updating the DNS vendor.
=> Added steps for testing without updating the DNS vendor to TESTING.md

controller/customdomain_controller.go, controller/customdomain_controller_test.go, go.mod, go.sum
Completes: https://issues.redhat.com/browse/OSD-7562 and issue #68 
---
Adds an additional watch call to the CustomDomain controller which reconciles on events to Secrets. 
Events are filtered to only match Secrets labeled with the `managedLabel`, which is used to map a reconcile against the appropriate CustomDomain, whose name is the key of the `managedLabel`.
=> OSD-7562 - Reconcile when secrets are updated

README.md
I've been referring so many people to the diagram in https://github.com/openshift/ops-sop/blob/master/v4/alerts/HAProxyDown.md I finally thought to put it where it belongs 😛 
Also Go 1.13 and Operator-SDK v0.16.0 aren't accurate anymore
=> Add diagram for how the CR interacts with IngressControllers and update prereqs

api/v1alpha1/customdomain_types.go, controller/customdomain_controller.go, controller/customdomain_controller_test.go, deploy/crds/managed.openshift.io_customdomains.yaml
In this commit, I added options to allow to specify an NLB as a LoadBalancer when custom domain operator is creating the IngressController via CustomDomain CR.  https://issues.redhat.com/browse/OSD-13676
=> [OSD-13676] Added option for Classic and NLB load balancer

TESTING.md
In this commit, I corrected the command used for testing custom domains.
Instead of  
incorrect:
curl -k https://hello-openshift-tls-my-project.stuff.alice.io --resolve hello-openshift-tls-my-project.apps.acme.io:443:<IP of the endpoint>
correct:
curl -k https://hello-openshift-tls-my-project.apps.acme.io --resolve hello-openshift-tls-my-project.apps.acme.io:443:<IP of the endpoint>
=> Corrected command used for testing custom domains

TESTING.md
In this commit, I updated the commands used in testing because of the recant changes i.e. logging in with backplane and having to elevate to cluster-admin for creating and describing resources.
=> Updating doc to contain exact commands to be run for testing

hack/olm-registry/olm-artifacts-template.yaml
As part of [SDE-1768](https://issues.redhat.com/browse/SDE-1768) and [OSD-16275](https://issues.redhat.com/browse/OSD-16275), we need to deprecate the Custom Domains Operator on all 4.13+ installs. This pull request adds a match expression for all of the available clusters up to v4.12 in `ocm list clusters`. 
I have done a companion document [here](https://docs.google.com/document/d/1FXMeET417Pv-031EEHqhr3ZdlxyEPUwaSDyxZeSEdyY/edit) which walks through how to set up a Hive installation on an OSD cluster, and test the `SelectorSyncSet` not deploying to a fresh v4.13 cluster. 
Any feedback and/or suggestions are most welcome.
=> Deprecate the custom domains operator on v4.13+

hack/olm-registry/olm-artifacts-template.yaml
Reverts openshift/custom-domains-operator#103. 
This is due to the 4.13 GA timeline clashing with the [SDE-1768](https://issues.redhat.com/browse/SDE-1768?focusedId=22248454&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-22248454) timeline. Will be revisited in a future pull request.
=> Revert "Deprecate the custom domains operator on v4.13+"

hack/olm-registry/olm-artifacts-template.yaml
As part of [SDE-1768](https://issues.redhat.com/browse/SDE-1768) and [OSD-16275](https://issues.redhat.com/browse/OSD-16275), we need to deprecate the Custom Domains Operator for any cluster with the new ingress feature enabled. 
The OCM team have agreed that for all new clusters with this capability will be indicated with a cluster deployment label, `ext-managed.openshift.io/legacy-ingress-support: false`. See https://gitlab.cee.redhat.com/service/uhc-clusters-service/-/merge_requests/6008
This means that if a cluster deployment either does not have the label, or has the label set to true, we deploy the CDO as normal (currently all clusters satisfy this condition). If the label exists and is set to `false`, we do not deploy the CDO. 
TLDR: do not deploy the custom domains operator if …
=> Deprecate CDO on clusters with ingress feature flag

examples/other_resources/00_namespace.yaml, hack/olm-registry/olm-artifacts-template.yaml
This sets pod security admission labels. Currently, none are set and starting with OpenShift 4.13 this generates warnings in Telemetry. This fixes it.
Refer to https://kubernetes.io/docs/concepts/security/pod-security-standards/ to further tighten the labels potentially to the recommended `restricted` level.
The labels were determined by using the https://github.com/stlaz/psachecker tool.
=> [AUTH-388] set pod security admission labels for namespace

api/v1alpha1/customdomain_types.go, controller/customdomain_controller.go, controller/customdomain_controller_test.go
https://issues.redhat.com/browse/OSD-17042
---
Adds logic which updates a custom-domain's ingresscontroller loadbalancer configuration if it's found to be set incorrectly. This update is only performed on AWS loadbalancers, as the timeout is not configurable in GCP.
=> Update LB timeout when set incorrectly

controller/customdomain_controller.go, controller/customdomain_utils.go, osde2e/custom_domains_operator_tests.go
with the deprecation, the tests need to be skipped
[SDCICD-1133](https://issues.redhat.com//browse/SDCICD-1133)
PR to skip on osde2e as well: https://github.com/openshift/osde2e/pull/2109
`AfterEach` needed to be moved to a `DeferCleanup` to be skipped properly, otherwise it would fail while trying to delete the resources.
=> osde2e: skip on >=4.13

osde2e/custom_domains_operator_tests.go
[SDCICD-1142](https://issues.redhat.com//browse/SDCICD-1142)
Fix broken CDO e2e test.
The test spec runs a tear down routine deleting custom domain, which is not created for the "operator upgrade test" spec. 
So, the teardown fails. 
Separating that spec from the other specs which need that teardown.
=> Fix broken e2e tear down

README.md, controller/customdomain_controller_test.go, controller/customdomain_utils.go
Allows CDO-managed IngressControllers to schedule onto both `infra` and `worker` nodes when moving into the new 'Managed Ingress v2' environment. 
Fixes https://issues.redhat.com/browse/OSD-19622
=> Allow CDO IngressControllers to schedule on worker and infra nodes when managed ingress is enabled

hack/olm-registry/olm-artifacts-template.yaml
the CatalogSource spec does not define `affinity` or `tolerations` at
the `spec` level. That is already set in the `grpcPodConfig`
https://docs.openshift.com/container-platform/4.14/rest_api/operatorhub_apis/catalogsource-operators-coreos-com-v1alpha1.html
https://issues.redhat.com/browse/SDCICD-1178
Signed-off-by: Brady Pratt <bpratt@redhat.com>
=> SDCICD-1178: remove affinity/tolerations from CatalogSource

main.go
Resolves https://issues.redhat.com/browse/OSD-22891
Adjust the `SyncPeriod` for the Custom Domains controller from 10 hours (the default) to 15 minutes, so that any label changes to *non-watched* objects (like the `openshift-custom-domains-operator` namespace) that may occur are propagated down into the logic of the controller quickly.
=> Adjust reconcile period of custom domain controller to pick up legacy ingress label changes

osde2e/custom_domains_operator_tests.go
What type of PR is this?
Feature Enhancement
What this PR does / why we need it
This PR introduces a mechanism to mark upgrades as "pending" if outdated configurations are detected in the Custom Domains Operator.
Ensures upgrades with stale or obsolete settings are identified and flagged.
Prevents potential upgrade failures by pausing the process until the configurations are updated.
Which Jira/Github issue(s) this PR fixes?
Part of [OSD-26388](https://issues.redhat.com//browse/OSD-26388)
Special notes for your reviewer
Implemented logic to check and flag outdated configurations during the upgrade process.
Verified functionality through testing to confirm upgrades are appropriately marked as "pending" when configurations are outdated.
=> Mark Upgrade as pending for outdated configurations

build/Dockerfile, build/Dockerfile.olm-registry, deploy/04_operator.yaml
Added limits to CPU and memory for Deployment of the operator.
To come up with the values I Deployed a test cluster and checked the CPU and memory consumption of the operator's normal behavior for a day. After I followed the process to deploy a new custom domain and check if there were any considerable spikes in resource consumption by the operator. The results were similar to the operator doing its normal functions. no considerable spikes.
=> Added limits to cpu and memory for Deployment

.tekton/custom-domains-operator-pull-request.yaml, .tekton/custom-domains-operator-push.yaml
Fix for a bug (Removing the on-cel-expression to build both controller and e2e components for each commit)
Make sure the konflux build triggered for both controller and e2e components.
Ref [OSD-30779](https://issues.redhat.com//browse/OSD-30799)
=> OSD-30799: Removing the on-cel-expression for tekton files
